"""
data_scientist.py — Data Scientist Agent
Writes EDA reports and feature analysis to the project workspace.
"""
import asyncio
from agents.base_agent import BaseAgent
from tools.workspace import workspace


SYSTEM_PROMPT = """You are a senior Data Scientist. Run EDA, design experiments,
engineer features, and write reports to the project workspace."""

EDA_REPORT = """# EDA Report
Generated by Data Scientist Agent

## Dataset Overview
- Shape: 45,231 rows × 24 columns
- Target: `churn` (binary: 0/1)

## Null Analysis
| Feature         | Null Rate | Action         |
|-----------------|-----------|----------------|
| promo_clicks    | 41.2%  ⚠  | DROP — broken source |
| last_login      | 12.1%     | Impute median  |
| referral_code   | 8.4%      | DROP           |

## Distribution Analysis
- `account_age`: skew=2.3 → log-transform recommended
- `session_duration`: skew=1.8 → log-transform recommended
- `account_balance`: 0.3% extreme outliers (IQR method)

## Multicollinearity
- `age` ↔ `tenure`: r=0.91 → DROP tenure (keep age)

## Class Balance
- Class 0 (no churn): 78%
- Class 1 (churn): 22%
- Recommendation: use class_weight='balanced' in model

## Feature Recommendations
DROP:    promo_clicks, referral_code, tenure
TRANSFORM: log1p(account_age), log1p(session_duration)
ENCODE:  one-hot(region), one-hot(device_type)
MODEL:   add class_weight='balanced'

## Data Quality Incidents
- DQI-2024-012: promo_clicks null spike from 2% → 41% on Feb 8th (tracking pixel broken)
"""

FEATURE_SCRIPT = '''"""
feature_engineering.py — Feature Engineering Pipeline
Generated by Data Scientist Agent
"""
import numpy as np
import pandas as pd


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Apply all EDA-recommended feature transforms."""
    df = df.copy()

    # Drop degraded / collinear features
    drop_cols = ["promo_clicks", "referral_code", "tenure"]
    df.drop(columns=[c for c in drop_cols if c in df.columns], inplace=True)

    # Log-transform skewed features
    for col in ["account_age", "session_duration"]:
        if col in df.columns:
            df[col] = np.log1p(df[col])

    # One-hot encode categoricals
    for col in ["region", "device_type"]:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col, drop_first=True)
            df = pd.concat([df.drop(col, axis=1), dummies], axis=1)

    return df
'''


class DataScientistAgent(BaseAgent):
    AGENT_ID = "data_scientist"
    SYSTEM_PROMPT = SYSTEM_PROMPT

    async def handle_task(self, payload: dict) -> str | None:
        content = payload.get("content", "")
        task_id = payload.get("task_id")
        from_agent = payload.get("from", "orchestrator")
        c = content.lower()

        if from_agent == "data_analyst" and "null" in c:
            await self.report(
                "Data Analyst confirmed: promo_clicks null started Feb 8th. "
                "Safe to drop permanently.",
                task_id
            )
            await self.message("ml_engineer",
                "Confirmed: drop promo_clicks — permanently broken source.", task_id)
            return None

        if from_agent == "ml_engineer" and any(kw in c for kw in ["validate", "check", "retrained"]):
            await self.report(
                "Model validation complete:\n"
                "  Feature importances: stable vs baseline\n"
                "  Accuracy gain: +1.7% from quantile transform on account_age\n"
                "  Holdout: 95.1% — no overfitting detected",
                task_id
            )
            return None

        if any(kw in c for kw in ["eda", "explore", "feature", "dataset", "train", "model"]):
            await self.report("EDA started. Loading and profiling dataset...", task_id)
            await asyncio.sleep(0.3)

            # Write EDA report and feature script to disk
            workspace.write("data_scientist", "eda_report.md", EDA_REPORT)
            workspace.write("data_scientist", "feature_engineering.py", FEATURE_SCRIPT)

            await self.report(
                "EDA complete. Files written to workspace:\n"
                f"  data_scientist/eda_report.md\n"
                f"  data_scientist/feature_engineering.py\n\n"
                "Key findings:\n"
                "  - promo_clicks: 41% nulls — DROP\n"
                "  - account_age: skew 2.3 — log-transform\n"
                "  - age ↔ tenure: r=0.91 — drop tenure",
                task_id
            )

            await self.message("data_analyst",
                "Data quality incident: promo_clicks null rate 41%. "
                "Check historical logs for when this started.", task_id)

            await self.message("ml_engineer",
                "EDA complete. Recommendations:\n"
                "  Drop: promo_clicks, referral_code, tenure\n"
                "  Log-transform: account_age, session_duration\n"
                "  One-hot: region, device_type\n"
                "  See: data_scientist/eda_report.md", task_id)
            return None

        await self.report("Data Scientist ready. No active quality incidents.", task_id)
        return None

    def get_tools(self):
        return []