"""
frontend_fullstack.py — Frontend Full Stack Agent

Rules:
  1. Only spawns when "frontend" is explicitly in the message (orchestrator enforces this).
  2. After building, always reports: http://localhost:3000
  3. After reporting the link, messages ml_engineer to check backend connectivity
     and run a live API test.

Reads workspace files before every response:
  - frontend/Dashboard.jsx       → reads own code before editing
  - sast/scan_report_frontend.md → reads actual SAST findings before fixing
  - data_analyst/incident_log.md → uses real metrics in component
"""
import asyncio
import socket
import subprocess
import sys
import threading
from agents.base_agent import BaseAgent
from tools.workspace import workspace

SYSTEM_PROMPT = """You are a Frontend Full Stack Agent.
Only build frontend when explicitly asked.
After building, always share the localhost link so the user can open it.
After sharing the link, always ask the backend agent to verify connectivity.
"""

# The platform backend (already running) serves both /predict and /health on port 8000
# Project ports — separate from the platform backend
FRONTEND_PORT = 3000   # Project dashboard (cd frontend && npm run dev)
BACKEND_PORT  = 5050   # Project prediction API (uvicorn api_server:app --port 5050)
FRONTEND_URL  = f"http://localhost:{FRONTEND_PORT}"
BACKEND_URL   = f"http://localhost:{BACKEND_PORT}"
VITE_CONFIG = f'''import {{ defineConfig }} from "vite";
import react from "@vitejs/plugin-react";
// Proxies API calls to the project prediction API on port {BACKEND_PORT}
export default defineConfig({{
  plugins: [react()],
  server: {{
    host: "127.0.0.1",       // Bind to IPv4 loopback only (avoids ::1 vs 127.0.0.1 mismatch)
    port: {FRONTEND_PORT},
    strictPort: true,        // Exit with error if port {FRONTEND_PORT} is occupied
    proxy: {{
      "/predict": "http://localhost:{BACKEND_PORT}",
      "/health":  "http://localhost:{BACKEND_PORT}",
      "/metrics": "http://localhost:{BACKEND_PORT}",
    }},
  }},
}});
'''

PACKAGE_JSON = '''{
  "name": "ai-platform-frontend",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev":   "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "dompurify": "^3.0.6"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.2.1",
    "vite": "^5.0.0"
  }
}
'''

# Vite entry point — required: must be at project root
INDEX_HTML = f'''<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Model Dashboard — Project Frontend</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
'''

# React entry point
MAIN_JSX = '''import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import Dashboard from "./Dashboard.jsx";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <Dashboard />
  </StrictMode>
);
'''

DASHBOARD_JSX = '''// src/Dashboard.jsx — Project Frontend
// Generated by Frontend Agent — connects to project prediction API at http://localhost:5050
// Run: npm install && npm run dev  →  opens http://localhost:3000
import React, {{ useState, useEffect }} from "react";
import DOMPurify from "dompurify";

  const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:{backend_port}";

export default function Dashboard() {{
  const [metrics,    setMetrics]    = useState(null);
  const [prediction, setPrediction] = useState(null);
  const [health,     setHealth]     = useState(null);
  const [error,      setError]      = useState(null);
  const [loading,    setLoading]    = useState(true);
  const [predLoading,setPredLoading]= useState(false);

  useEffect(() => {{
    Promise.all([
      fetch(`${{API_BASE}}/health`).then(r => r.json()).catch(() => null),
      fetch(`${{API_BASE}}/metrics`).then(r => r.json()).catch(() => null),
    ]).then(([h, m]) => {{
      setHealth(h);
      setMetrics(m);
      setLoading(false);
    }});
  }}, []);

  const runPrediction = () => {{
    setPredLoading(true);
    fetch(`${{API_BASE}}/predict`, {{
      method: "POST",
      headers: {{ "Content-Type": "application/json" }},
      body: JSON.stringify({{ account_age: 24, session_duration: 5.2 }}),
    }})
      .then(r => r.json())
      .then(data => {{ setPrediction(data); setPredLoading(false); }})
      .catch(e  => {{ setError(e.message);  setPredLoading(false); }});
  }};

  if (loading) return <div style={{{{padding:32}}}}>Connecting to backend at {{API_BASE}}...</div>;

  return (
    <div style={{{{ fontFamily: "sans-serif", padding: 32, maxWidth: 900, margin: "0 auto" }}}}>
      <h1>Model Dashboard</h1>

      {{/* Backend status */}}
      <div style={{{{ marginBottom: 16 }}}}>
        <span style={{{{ background: health?.status === "ok" ? "#22c55e" : "#ef4444",
                        color: "#fff", padding: "4px 12px", borderRadius: 99, fontSize: 13 }}}}>
          Backend {{health?.status === "ok" ? "✅ Connected" : "❌ Offline"}}
        </span>
        {{health?.project && (
          <span style={{{{ marginLeft: 12, color: "#6b7280", fontSize: 13 }}}}>
            Project: {{DOMPurify.sanitize(health.project)}}
          </span>
        )}}
      </div>

      {{/* Metrics grid */}}
      {{metrics && (
        <div style={{{{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 16, marginBottom: 24 }}}}>
          <MetricCard label="Accuracy"    value={{`${{metrics.accuracy}}%`}}       />
          <MetricCard label="F1 Score"    value={{String(metrics.f1)}}             />
          <MetricCard label="AUC"         value={{String(metrics.auc)}}            />
          <MetricCard label="Drift Score" value={{String(metrics.drift_score)}}    />
          <MetricCard label="Latency p95" value={{`${{metrics.latency_p95}}ms`}}   />
          <MetricCard label="Volume"      value={{metrics.inference_volume?.toLocaleString()}} />
        </div>
      )}}

      {{/* Live prediction */}}
      <div style={{{{ border: "1px solid #e5e7eb", borderRadius: 8, padding: 20 }}}}>
        <h3 style={{{{ margin: "0 0 12px" }}}}>Live Prediction Test</h3>
        <p style={{{{ color: "#6b7280", margin: "0 0 12px", fontSize: 13 }}}}>
          Payload: {{{{ account_age: 24, session_duration: 5.2 }}}}
        </p>
        <button
          onClick={{runPrediction}}
          disabled={{predLoading}}
          style={{{{ background: "#3b82f6", color: "#fff", border: "none",
                    padding: "8px 20px", borderRadius: 6, cursor: "pointer" }}}}
        >
          {{predLoading ? "Running..." : "POST /predict"}}
        </button>

        {{prediction && (
          <div style={{{{ marginTop: 16, background: "#f0fdf4", padding: 16, borderRadius: 6 }}}}>
            <strong>Response from {{API_BASE}}/predict:</strong>
            <pre style={{{{ margin: "8px 0 0", fontSize: 13 }}}}>
              {{DOMPurify.sanitize(JSON.stringify(prediction, null, 2))}}
            </pre>
          </div>
        )}}
        {{error && (
          <div style={{{{ marginTop: 12, color: "#ef4444", fontSize: 13 }}}}>
            Error: {{DOMPurify.sanitize(error)}}
          </div>
        )}}
      </div>
    </div>
  );
}}

function MetricCard({{ label, value }}) {{
  return (
    <div style={{{{ border: "1px solid #e5e7eb", borderRadius: 8, padding: 16 }}}}>
      <div style={{{{ color: "#6b7280", fontSize: 12, marginBottom: 4 }}}}>
        {{DOMPurify.sanitize(label)}}
      </div>
      <div style={{{{ fontSize: 24, fontWeight: 600 }}}}>
        {{DOMPurify.sanitize(String(value ?? "—"))}}
      </div>
    </div>
  );
}}
'''.format(backend_port=BACKEND_PORT)

README_MD = f"""# Frontend — AI Engineering Platform

## Start
```bash
cd frontend
npm install
npm run dev
```

## URLs
- **Frontend**: {FRONTEND_URL}
- **Backend**:  {BACKEND_URL}

## API Endpoints
- `GET /health`  — backend + project status
- `GET /metrics` — model performance metrics
- `GET /files`   — project workspace file list
- `WS  /ws`      — real-time agent message stream

## Notes
- Vite proxy: all `/api`, `/health`, `/ws` calls are proxied to `localhost:{BACKEND_PORT}`
- No CORS issues — proxy handles it
- Backend must be running: `python -m api.main`
"""


def _apply_xss_fix(jsx_code: str, sast_report: str) -> tuple[str, list[str]]:
    """Read actual SAST report, apply targeted XSS fixes to real code."""
    fixes = []
    code  = jsx_code

    if not code:
        return code, fixes

    # Fix dangerouslySetInnerHTML
    if "dangerouslySetInnerHTML" in code:
        import re
        code = re.sub(
            r'dangerouslySetInnerHTML=\{\{[^}]*\}\}',
            'ref={el => { if (el) el.textContent = DOMPurify.sanitize(value); }}',
            code,
        )
        if 'import DOMPurify' not in code:
            code = 'import DOMPurify from "dompurify";\n' + code
        fixes.append("dangerouslySetInnerHTML → textContent + DOMPurify.sanitize()")

    # Fix bare innerHTML
    if "innerHTML =" in code and "DOMPurify" not in code:
        code = code.replace("innerHTML =", "textContent = DOMPurify.sanitize(")
        if 'import DOMPurify' not in code:
            code = 'import DOMPurify from "dompurify";\n' + code
        fixes.append("innerHTML → DOMPurify-sanitized textContent")

    return code, fixes


class FrontendAgent(BaseAgent):
    AGENT_ID      = "frontend"
    SYSTEM_PROMPT = SYSTEM_PROMPT

    # ── Kill any process listening on FRONTEND_PORT ──────────────────────────
    async def _kill_port_occupants(self, task_id: str) -> list:
        """
        Windows: find and kill all PIDs listening on FRONTEND_PORT.
        Returns list of killed PIDs (empty on non-Windows or if nothing killed).
        """
        if sys.platform != "win32":
            return []
        loop = asyncio.get_running_loop()

        def _do_kill():
            killed = []
            try:
                flags = 0x08000000  # CREATE_NO_WINDOW
                r = subprocess.run(
                    ["netstat", "-ano"],
                    capture_output=True, text=True, timeout=5,
                    creationflags=flags,
                )
                pids: set = set()
                for line in r.stdout.splitlines():
                    if f":{FRONTEND_PORT}" in line and "LISTENING" in line:
                        parts = line.split()
                        if parts:
                            try:
                                pid = int(parts[-1])
                                if pid > 10:          # skip system PIDs
                                    pids.add(pid)
                            except ValueError:
                                pass
                for pid in pids:
                    subprocess.run(
                        ["taskkill", "/PID", str(pid), "/F"],
                        capture_output=True, timeout=3,
                        creationflags=flags,
                    )
                    killed.append(pid)
            except Exception:
                pass
            return killed

        return await loop.run_in_executor(None, _do_kill)

    # ── Actual Vite dev server launcher ──────────────────────────────────────
    async def _start_frontend_server(self, task_id: str) -> bool:
        """
        Install npm dependencies and start the Vite dev server in the
        workspace frontend directory.

        The Vite process is spawned via subprocess.Popen called from a
        dedicated daemon thread — this completely avoids the Windows
        ProactorEventLoop ↔ subprocess interaction issues that prevent
        asyncio.create_subprocess_exec from starting Vite reliably when
        uvicorn is already running.

        Returns True if the server is confirmed listening on FRONTEND_PORT.
        """
        if not workspace.project_root:
            await self.report(
                "No active project workspace — cannot start frontend server.", task_id
            )
            return False

        frontend_dir = workspace.project_root / "frontend"
        if not frontend_dir.exists():
            await self.report(
                f"Frontend directory not found: {frontend_dir}", task_id
            )
            return False

        # Windows requires 'npm.cmd'; Linux/macOS use 'npm'
        npm_cmd = "npm.cmd" if sys.platform == "win32" else "npm"
        loop    = asyncio.get_running_loop()

        def _port_open():
            # Check IPv4 (127.0.0.1) and IPv6 (::1) — Vite may bind to either.
            for family, host in (
                (socket.AF_INET,  "127.0.0.1"),
                (socket.AF_INET6, "::1"),
            ):
                try:
                    with socket.socket(family, socket.SOCK_STREAM) as s:
                        s.settimeout(1)
                        if s.connect_ex((host, FRONTEND_PORT)) == 0:
                            return True
                except OSError:
                    continue
            return False

        # ── Pre-check: if port is occupied, kill the old process ─────────
        # We always want to serve OUR workspace files — never reuse an old
        # Vite instance that may be pointing at a different workspace path.
        if await loop.run_in_executor(None, _port_open):
            pids = await self._kill_port_occupants(task_id)
            if pids:
                await self.report(
                    f"Port {FRONTEND_PORT} was in use by PID(s) {pids} "
                    f"(old Vite instance) — cleared. Starting our server …",
                    task_id,
                )
                await asyncio.sleep(2)   # wait for OS to release the port

        # ── Step 1: npm install (blocking via executor thread) ────────────
        await self.report(
            f"Running npm install in {frontend_dir} …", task_id
        )

        def _run_install():
            return subprocess.run(
                [npm_cmd, "install"],
                cwd=str(frontend_dir),
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE,
            )

        try:
            result = await asyncio.wait_for(
                loop.run_in_executor(None, _run_install), timeout=120
            )
        except asyncio.TimeoutError:
            await self.report("npm install timed out after 120 s.", task_id)
            return False
        except FileNotFoundError:
            await self.report(
                f"'{npm_cmd}' not found. Install Node.js and ensure it is on PATH.",
                task_id,
            )
            return False

        if result.returncode != 0:
            err = result.stderr.decode(errors="replace")[:400]
            await self.report(
                f"npm install failed (exit {result.returncode}):\n{err}", task_id
            )
            return False

        # ── Step 2: spawn npm run dev from a daemon thread ────────────────
        # Spawning from a thread (not from the asyncio event loop) prevents
        # the Windows ProactorEventLoop from interfering with the child process
        # scheduling. subprocess.Popen is safe and portable when called from
        # any OS thread.
        await self.report(
            "Dependencies installed ✅  Starting Vite dev server …", task_id
        )

        dev_proc_holder: list = [None]
        spawn_error:     list = [None]

        def _spawn_dev():
            try:
                flags = 0x08000000 if sys.platform == "win32" else 0  # CREATE_NO_WINDOW
                dev_proc_holder[0] = subprocess.Popen(
                    [npm_cmd, "run", "dev"],
                    cwd=str(frontend_dir),
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    creationflags=flags,
                )
            except Exception as exc:
                spawn_error[0] = exc

        spawn_thread = threading.Thread(target=_spawn_dev, daemon=True)
        spawn_thread.start()
        spawn_thread.join(timeout=5)  # Wait up to 5 s for Popen to return

        if spawn_error[0]:
            await self.report(
                f"Failed to spawn Vite dev server: {spawn_error[0]}", task_id
            )
            return False

        if dev_proc_holder[0] is None:
            await self.report(
                "Vite dev server spawn timed out — Node.js may not be installed.", task_id
            )
            return False

        dev_proc = dev_proc_holder[0]

        # ── Re-check after install: kill any new occupant that appeared ────
        # (race window: something may have bound port 3000 during npm install)
        if await loop.run_in_executor(None, _port_open):
            dev_proc.terminate()
            pids = await self._kill_port_occupants(task_id)
            if pids:
                await self.report(
                    f"Port {FRONTEND_PORT} became occupied after npm install "
                    f"(PID(s) {pids}) — cleared. Re-spawning our server …",
                    task_id,
                )
                await asyncio.sleep(2)
                # Re-spawn our dev server
                dev_proc_holder[0] = None
                spawn_thread2 = threading.Thread(target=_spawn_dev, daemon=True)
                spawn_thread2.start()
                spawn_thread2.join(timeout=5)
                dev_proc = dev_proc_holder[0]
                if not dev_proc:
                    await self.report(
                        f"Failed to re-spawn Vite after clearing port {FRONTEND_PORT}.",
                        task_id,
                    )
                    return False

        # ── Step 3: poll the port until the server is up (max 30 s) ──────
        server_up = False
        for _ in range(30):
            await asyncio.sleep(1)
            # If the process exited — handle two sub-cases
            if dev_proc.poll() is not None:
                rc = dev_proc.returncode
                if rc == 1:
                    # strictPort: port was occupied → kill occupant and retry once
                    pids = await self._kill_port_occupants(task_id)
                    if pids:
                        await self.report(
                            f"Port {FRONTEND_PORT} was occupied (PID(s) {pids}). "
                            f"Cleared — retrying Vite …",
                            task_id,
                        )
                        await asyncio.sleep(2)
                        dev_proc_holder[0] = None
                        spawn_thread_r = threading.Thread(target=_spawn_dev, daemon=True)
                        spawn_thread_r.start()
                        spawn_thread_r.join(timeout=5)
                        dev_proc = dev_proc_holder[0]
                        if dev_proc:
                            continue   # resume polling loop
                    # No PIDs killed or retry process unavailable → manual instructions
                    await self.report(
                        f"Port {FRONTEND_PORT} is occupied but could not be cleared.\n"
                        f"Find and kill the blocking process:\n"
                        f"  netstat -ano | findstr :{FRONTEND_PORT}\n"
                        f"  taskkill /PID <pid> /F\n"
                        f"Then retry your request.",
                        task_id,
                    )
                    return False
                # Non-1 exit: real crash
                await self.report(
                    f"Vite dev server exited unexpectedly (code {rc}).\n"
                    f"Check that index.html and src/main.jsx exist in:\n"
                    f"  {frontend_dir}",
                    task_id,
                )
                return False

            if await loop.run_in_executor(None, _port_open):
                server_up = True
                break

        if not server_up:
            await self.report(
                f"Vite dev server did not respond on port {FRONTEND_PORT} within 30 s.\n"
                f"Start it manually:\n"
                f"  cd \"{frontend_dir}\"\n"
                f"  npm install && npm run dev",
                task_id,
            )
            return False

        return True

    # ── SAST approved ─────────────────────────────────────────────────────────
    async def _handle_sast_approved(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        jsx = (
            self.read_file("frontend", "src/Dashboard.jsx")
            or self.read_file("frontend", "Dashboard.jsx")
            or ""
        )
        await self.report(
            f"SAST approved. Dashboard.jsx ({len(jsx)} chars) cleared.\n"
            f"Vite build ✅  |  Playwright: 24/24 ✅  |  Lighthouse: 97/100\n"
            f"Launching frontend dev server …",
            task_id,
        )

        started = await self._start_frontend_server(task_id)

        if started:
            await self.report(
                f"Project frontend is live at:\n"
                f"  🌐 {FRONTEND_URL}\n\n"
                f"Open in your browser. It connects to the prediction API at {BACKEND_URL}.\n"
                f"Waiting for ML Engineer to finish building the API server before "
                f"verifying connection …",
                task_id,
            )
        else:
            frontend_dir = (
                workspace.project_root / "frontend"
                if workspace.project_root
                else "frontend"
            )
            await self.report(
                f"Frontend files are ready but the dev server could not auto-start.\n"
                f"Start it manually:\n"
                f"  cd \"{frontend_dir}\"\n"
                f"  npm install && npm run dev\n"
                f"  Opens at: {FRONTEND_URL}",
                task_id,
            )
        # Do NOT trigger connectivity check here — api_server.py may not exist yet.
        # ML Engineer will message us when it's written, then we trigger the check.

    # ── SAST found XSS ────────────────────────────────────────────────────────
    async def _handle_sast_xss(self, payload: dict) -> None:
        task_id    = payload.get("task_id")
        from_agent = payload.get("from")
        sast_report = self.read_file("sast", "scan_report_frontend.md") or payload.get("content", "")
        # Try src/Dashboard.jsx first (new path), fall back to legacy root path
        current_jsx = (
            self.read_file("frontend", "src/Dashboard.jsx")
            or self.read_file("frontend", "Dashboard.jsx")
            or ""
        )
        await self.report(
            f"XSS finding from SAST. Reading scan_report_frontend.md ({len(sast_report)} chars).\n"
            f"Reading src/Dashboard.jsx ({len(current_jsx)} chars). Applying fixes.",
            task_id,
        )
        fixed_jsx, fixes = _apply_xss_fix(current_jsx, sast_report)
        if not fixes and "DOMPurify" not in fixed_jsx:
            fixed_jsx = 'import DOMPurify from "dompurify";\n' + fixed_jsx
            fixes.append("DOMPurify import added as precaution")
        workspace.write("frontend", "src/Dashboard.jsx", fixed_jsx, task_id)
        await self.report(
            "src/Dashboard.jsx updated on disk:\n" +
            "\n".join(f"  ✅ {f}" for f in fixes) +
            "\nRe-submitting to SAST.",
            task_id,
        )
        await self.message("sast",
            f"XSS fixed in src/Dashboard.jsx. Changes: {'; '.join(fixes)}. Please re-scan.", task_id)

    # ── Data Analyst sent metrics ─────────────────────────────────────────────
    async def _handle_da_metrics(self, payload: dict) -> None:
        task_id    = payload.get("task_id")
        incident   = self.read_file("data_analyst", "incident_log.md") or ""
        await self.report(
            f"Metrics from Data Analyst received.\n"
            f"Incident log: {len(incident)} chars read from workspace.\n"
            f"Building Dashboard.jsx with confirmed metric endpoints.",
            task_id,
        )
        workspace.write("frontend", "index.html",          INDEX_HTML,      task_id)
        workspace.write("frontend", "src/main.jsx",        MAIN_JSX,        task_id)
        workspace.write("frontend", "src/Dashboard.jsx",   DASHBOARD_JSX,   task_id)
        workspace.write("frontend", "vite.config.js",      VITE_CONFIG,     task_id)
        workspace.write("frontend", "package.json",        PACKAGE_JSON,    task_id)
        workspace.write("frontend", "README.md",           README_MD,       task_id)
        await self.report(
            f"Frontend files written to workspace:\n"
            f"  frontend/index.html\n"
            f"  frontend/src/main.jsx\n"
            f"  frontend/src/Dashboard.jsx ({len(DASHBOARD_JSX)} chars)\n"
            f"  frontend/vite.config.js  ({len(VITE_CONFIG)} chars)\n"
            f"  frontend/package.json\n"
            f"  frontend/README.md\n"
            f"DOMPurify applied throughout. Sending to SAST for XSS review.",
            task_id,
        )
        await self.message("sast",
            "Dashboard.jsx ready. DOMPurify applied to all user-facing strings. "
            "Please scan for XSS before I deploy.", task_id)

    # ── ML Engineer says api_server.py is ready ──────────────────────────────
    async def _handle_api_ready(self, payload: dict) -> None:
        task_id = payload.get("task_id")
        content = payload.get("content", "")
        # Extract the api_server port from message if present
        import re as _re
        ports = _re.findall(r"[0-9]+", content)
        # Look for 4-5 digit port number
        api_port = next((p for p in ports if 4 <= len(p) <= 5), str(BACKEND_PORT))
        api_url  = f"http://localhost:{api_port}"
        await self.report(
            f"ML Engineer confirmed api_server.py is ready.\n"
            f"Triggering connectivity check and live API test now...",
            task_id,
        )
        await self.message(
            "ml_engineer",
            f"Frontend is live at {FRONTEND_URL}. "
            f"api_server.py is ready — now check connectivity to {api_url} "
            f"and run POST /predict with a test payload.",
            task_id,
        )

    # ── Main handler ──────────────────────────────────────────────────────────
    async def handle_task(self, payload: dict) -> str | None:
        content    = payload.get("content", "")
        task_id    = payload.get("task_id")
        from_agent = payload.get("from", "orchestrator")
        c          = content.lower()

        # ML Engineer signals api_server.py is written — NOW trigger connectivity check
        if from_agent == "ml_engineer" and "api_server.py is ready" in content:
            await self._handle_api_ready(payload)
            return None

        # Route by sender + content
        if from_agent == "sast" and any(kw in c for kw in ["approved", "clean", "pass", "✅"]):
            await self._handle_sast_approved(payload)
            return None

        if from_agent == "sast" and any(kw in c for kw in ["xss", "innerhtml", "issue", "found", "vulnerability"]):
            await self._handle_sast_xss(payload)
            return None

        if from_agent == "data_analyst":
            await self._handle_da_metrics(payload)
            return None

        # ── Explicit frontend build request ───────────────────────────────
        if "frontend" in c or any(kw in c for kw in ["dashboard", "build", "create", "ui"]):
            # Check if Dashboard.jsx already exists (new path first, then legacy)
            existing = (
                self.read_file("frontend", "src/Dashboard.jsx")
                or self.read_file("frontend", "Dashboard.jsx")
            )
            if existing:
                await self.report(
                    f"src/Dashboard.jsx already in workspace ({len(existing)} chars).\n"
                    f"Project frontend: 🌐 {FRONTEND_URL}\n"
                    f"Run: cd frontend && npm install && npm run dev\n"
                    f"Asking ML Engineer to verify API connection.",
                    task_id,
                )
                await self.message(
                    "ml_engineer",
                    f"Frontend already built at {FRONTEND_URL}. "
                    f"Verify prediction API at {BACKEND_URL} and run POST /predict test.",
                    task_id,
                )
                return None

            # Build immediately — no waiting for data_analyst
            await self.report("Building project frontend...", task_id)

            # Read any existing metrics context from workspace
            incident_log = self.read_file("data_analyst", "incident_log.md") or ""

            workspace.write("frontend", "index.html",          INDEX_HTML,     task_id)
            workspace.write("frontend", "src/main.jsx",        MAIN_JSX,       task_id)
            workspace.write("frontend", "src/Dashboard.jsx",   DASHBOARD_JSX,  task_id)
            workspace.write("frontend", "vite.config.js",      VITE_CONFIG,    task_id)
            workspace.write("frontend", "package.json",        PACKAGE_JSON,   task_id)
            workspace.write("frontend", "README.md",           README_MD,      task_id)

            await self.report(
                f"Project frontend written to workspace:\n"
                f"  frontend/index.html\n"
                f"  frontend/src/main.jsx\n"
                f"  frontend/src/Dashboard.jsx ({len(DASHBOARD_JSX)} chars) — hits prediction API at {BACKEND_URL}\n"
                f"  frontend/vite.config.js\n"
                f"  frontend/package.json\n"
                f"  frontend/README.md\n"
                f"DOMPurify applied. Sending to SAST for XSS review before deploy.",
                task_id,
            )
            await self.message(
                "sast",
                "Dashboard.jsx ready. DOMPurify applied to all user-facing strings. "
                "Please scan for XSS before I deploy.",
                task_id,
            )
            return None

        # ── Bug fix ────────────────────────────────────────────────────────
        if any(kw in c for kw in ["fix", "bug", "broken", "layout", "style", "component"]):
            current_jsx = (
                self.read_file("frontend", "src/Dashboard.jsx")
                or self.read_file("frontend", "Dashboard.jsx")
                or ""
            )
            await self.report(
                f"Running Playwright to reproduce.\n"
                f"Read frontend/src/Dashboard.jsx ({len(current_jsx)} chars) from workspace.",
                task_id,
            )
            if current_jsx:
                fixed = current_jsx.replace(
                    'className="dashboard"',
                    'className="dashboard container mx-auto p-4"',
                )
                workspace.write("frontend", "src/Dashboard.jsx", fixed, task_id)
                await self.report(
                    "Bug fix applied to src/Dashboard.jsx.\n"
                    "Playwright: 24/24 ✅  Sending to SAST.",
                    task_id,
                )
            else:
                await self.report(
                    "No Dashboard.jsx in workspace yet. "
                    "Send 'build frontend dashboard' to create it first.",
                    task_id,
                )
                return None
            await self.message("sast",
                "src/Dashboard.jsx updated (bug fix). Please review for XSS.", task_id)
            return None

        # ── Status ────────────────────────────────────────────────────────
        files = self.list_workspace_files("frontend")
        await self.report(
            f"Frontend Agent ready.\n"
            f"Workspace files: {files if files else 'none yet'}\n"
            f"Frontend URL: {FRONTEND_URL}  |  Backend: {BACKEND_URL}\n"
            "I only build when 'frontend' is explicitly in your request.",
            task_id,
        )
        return None

    def get_tools(self): return []