"""
ml_engineer.py — ML Engineer Agent

Writes real .py files to the project workspace so you can open them
in VS Code and see exactly what the agent produced.
"""
import asyncio
from agents.base_agent import BaseAgent
from tools.workspace import workspace


SYSTEM_PROMPT = """You are a senior ML Engineer agent on an autonomous AI engineering platform.
Write complete, production-ready Python ML pipelines.
Always use the self-healing loop. Always get SAST approval before deploying.
"""

# ── Code templates the agent writes to disk ───────────────────────────────────

PIPELINE_CODE = '''"""
pipeline.py — Churn Prediction ML Pipeline
Generated by ML Engineer Agent
"""
import os
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import joblib

# ── Config ────────────────────────────────────────────────────────────────────
DB_CONN_STR = os.getenv("DB_CONN_STR")   # Never hardcode credentials
MODEL_PATH  = "model/churn_model.joblib"
DATA_PATH   = "data/churn_dataset.csv"

# ── Load data ─────────────────────────────────────────────────────────────────
def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    print(f"Loaded: {df.shape[0]} rows × {df.shape[1]} cols")
    return df

# ── Preprocess (based on EDA recommendations from Data Scientist) ─────────────
def preprocess(df: pd.DataFrame) -> tuple:
    # Drop features flagged in EDA
    drop_cols = ["promo_clicks", "referral_code", "tenure"]
    df = df.drop(columns=[c for c in drop_cols if c in df.columns])

    # Log-transform skewed features
    for col in ["account_age", "session_duration"]:
        if col in df.columns:
            df[col] = np.log1p(df[col])

    # One-hot encode categoricals
    for col in ["region", "device_type"]:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col, drop_first=True)
            df = pd.concat([df.drop(col, axis=1), dummies], axis=1)

    # Split features and target
    X = df.drop("churn", axis=1)
    y = df["churn"]
    return train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# ── Train ─────────────────────────────────────────────────────────────────────
def train(X_train, y_train) -> RandomForestClassifier:
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=12,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )
    model.fit(X_train, y_train)
    return model

# ── Evaluate ──────────────────────────────────────────────────────────────────
def evaluate(model, X_test, y_test) -> dict:
    y_pred  = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]
    metrics = {
        "accuracy": round(accuracy_score(y_test, y_pred), 4),
        "f1":       round(f1_score(y_test, y_pred), 4),
        "auc":      round(roc_auc_score(y_test, y_proba), 4),
    }
    print(f"Accuracy: {metrics['accuracy']} | F1: {metrics['f1']} | AUC: {metrics['auc']}")
    return metrics

# ── Save model ────────────────────────────────────────────────────────────────
def save_model(model, path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    joblib.dump(model, path)
    print(f"Model saved: {path}")

# ── Main ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    df = load_data(DATA_PATH)
    X_train, X_test, y_train, y_test = preprocess(df)
    model = train(X_train, y_train)
    metrics = evaluate(model, X_test, y_test)
    save_model(model, MODEL_PATH)
    print("Pipeline complete.", metrics)
'''

DEPLOY_CODE = '''"""
deploy.py — Model Deployment Script
Generated by ML Engineer Agent
Approved by SAST — no security issues found.
"""
import os
import joblib
import pandas as pd
from pathlib import Path

MODEL_PATH = os.getenv("MODEL_PATH", "model/churn_model.joblib")

def load_model():
    path = Path(os.path.abspath(MODEL_PATH))   # Sanitized path
    if not path.exists():
        raise FileNotFoundError(f"Model not found at {path}")
    return joblib.load(path)

def predict(features: dict) -> dict:
    model = load_model()
    df = pd.DataFrame([features])
    prediction = model.predict(df)[0]
    probability = model.predict_proba(df)[0][1]
    return {
        "churn": bool(prediction),
        "probability": round(float(probability), 4),
    }

if __name__ == "__main__":
    # Test prediction
    sample = {"account_age": 24, "session_duration": 5.2, "region_EU": 1}
    result = predict(sample)
    print(f"Prediction: {result}")
'''

REQUIREMENTS = '''# Requirements — generated by ML Engineer Agent
scikit-learn>=1.3.0
pandas>=2.0.0
numpy>=1.26.0
joblib>=1.3.0
requests>=2.31.0     # CVE-patched version (flagged by SAST)
python-dotenv>=1.0.0
'''


class MLEngineerAgent(BaseAgent):
    AGENT_ID = "ml_engineer"
    SYSTEM_PROMPT = SYSTEM_PROMPT

    async def handle_task(self, payload: dict) -> str | None:
        content = payload.get("content", "")
        task_id = payload.get("task_id")
        from_agent = payload.get("from", "orchestrator")
        c = content.lower()

        # SAST approved — write deploy script and finish
        if from_agent == "sast" and any(kw in c for kw in ["approved", "clean", "pass", "✅"]):
            await self.report("SAST approval received. Writing deploy script and committing...", task_id)

            workspace.write("ml_engineer", "deploy.py", DEPLOY_CODE)
            workspace.write("shared", "requirements.txt", REQUIREMENTS)

            await self.report(
                "Files written to project workspace:\n"
                "  ml_engineer/deploy.py\n"
                "  shared/requirements.txt\n"
                "Committed to feature/model-pipeline. CI started. Monitoring...",
                task_id
            )
            await asyncio.sleep(0.5)
            await self.report(
                "CI passed ✅  Model deployed to production.\n"
                "MLflow entry logged. Accuracy: 94.1%.\n"
                f"Project location: {workspace.project_root}",
                task_id
            )
            return None

        # SAST found issues — apply fix
        if from_agent == "sast" and any(kw in c for kw in ["issue", "found", "fix", "high", "medium", "critical"]):
            await self.report("SAST findings received. Applying fixes...", task_id)

            # Edit the deploy script in place
            if workspace.exists("ml_engineer", "deploy.py"):
                workspace.edit(
                    "ml_engineer", "deploy.py",
                    "MODEL_PATH = os.getenv",
                    "# SAST fix applied: path sanitized\nMODEL_PATH = os.getenv"
                )

            await self.report(
                "Fixes applied:\n"
                "  - Replaced hardcoded strings with os.getenv()\n"
                "  - Added path sanitization with os.path.abspath()\n"
                "Re-submitting to SAST for re-scan.",
                task_id
            )
            await self.message("sast", "Fixes applied. Please re-scan before I push.", task_id)
            return None

        # Data Scientist sent EDA recommendations
        if from_agent == "data_scientist" and any(kw in c for kw in ["eda", "feature", "recommend"]):
            await self.report(
                "EDA recommendations received. Updating pipeline with new feature transforms.",
                task_id
            )
            return None

        # Default — build pipeline
        if any(kw in c for kw in ["model", "train", "pipeline", "build", "churn", "predict"]):
            await self.report(
                "Starting pipeline build.\n"
                "  Dataset: loading from /data/...\n"
                "  Shape: 12,450 rows × 18 features\n"
                "  Baseline: RandomForestClassifier",
                task_id
            )

            # Write pipeline.py to disk RIGHT NOW
            workspace.write("ml_engineer", "pipeline.py", PIPELINE_CODE)
            await self.report(
                f"pipeline.py written to:\n"
                f"  {workspace.project_root}/ml_engineer/pipeline.py",
                task_id
            )

            # Ask Data Scientist for EDA
            await self.message(
                "data_scientist",
                "I'm building the ML pipeline. Can you run EDA and flag anything "
                "before I finalize feature selection?",
                task_id
            )

            await self.report("Running pipeline in E2B sandbox (mock)...", task_id)

            result = await self._run_with_healing(
                code=PIPELINE_CODE,
                task_id=task_id
            )

            if result["success"]:
                await self.report(
                    f"Sandbox run succeeded on attempt {result['attempts']}.\n"
                    "Accuracy: 94.1% | F1: 0.89 | AUC: 0.96\n"
                    "Requesting SAST scan before deploy.",
                    task_id
                )
                await self.message(
                    "sast",
                    "ML pipeline ready. Please scan before I push to GitHub.\n"
                    f"File: {workspace.project_root}/ml_engineer/pipeline.py",
                    task_id
                )
            return None

        await self.report(
            "ML Engineer ready. Last model: churn_v3 (94.1% accuracy). "
            "No active issues.",
            task_id
        )
        return None

    def get_tools(self):
        return []